def print_rook():
    print("  ___  ___  ___")
    print("  | |__| |__| |")
    print("  |           |")
    print("   \\_________/")
    print("    \\_______/")
    print("     |     |")
    print("     |     |")
    print("     |     |")
    print("     |     |")
    print("     |_____|")
    print("  __/       \\__")
    print(" /             \\")
    print("/_______________\\")

print_rook()
